# ALL UNITS EXPRESSED IN S.I.
V_RAIN = -10
V_RAIN_H = 0
V_RUNNER = 3.783

TIME_STEP = 'AUTO'  # LEAVE AS 'AUTO' IF WISHED TO BE AUTO-CALCULATED
TIME_PRECISION = 1  # CALCULATED DROP CREATION TIME / TIME_PRECISION FOR AUTO-CALCULATED TIME STEPS
TILT_PRECISION = 5
SCALE_WITH_DEPTH = True

RUNNER_HEIGHT = 1.78
RUNNER_WIDTH = 0.36
RUNNER_DEPTH = 0.20
RUNNER_TILT = 1.5  # RADIANS

DESTINATION_X_POS = 5
RAIN_DROP_GENERATION_HEIGHT = 5
RAIN_DROP_GENERATION_WIDTH = 4
INITIAL_RAIN_DROP_WIDTH = 5

RAINDROP_DENSITY = 550  # drops/m^3
COLLISION_ERROR = 1.0001  # WITHIN

SCREEN_SCALE = 100
DO_RENDER = True

